/**
 * eslintignore
 * @function eslintignore
 * @param {Object} config
 * @returns {Object}
 */
'use strict'

const _tmpl = require('./_tmpl')
const {spawnSync} = require('child_process')

/** @lends eslintignore */
function eslintignore (config = {}) {
  const { stdout } = spawnSync('git', ['grep', '--name-only', 'Code generated by coz. DO NOT EDIT.', '*.js', '*.jsx'])
  const cozFiles = stdout ? stdout.toString().split('\n').filter(Boolean).map(path => ({ path })) : []
  return {
    force: true,
    mode: '444',
    path: `.eslintignore`,
    data: {
      cozFiles,
    },
    tmpl: _tmpl('eslintignore.hbs'),
  }
}

module.exports = eslintignore
