// Code generated by coz. DO NOT EDIT.
/**
 * Templates for the-projects
 * @module the-templates
 */
'use strict'

const _interopRequireDefault = (obj) => obj && obj.__esModule ? obj : {default: obj}
const _d = (m) => _interopRequireDefault(m).default

const ctrl = _d(require('./Ctrl'))
const dialogs = _d(require('./Dialogs'))
const hook = _d(require('./Hook'))
const license = _d(require('./License'))
const readme = _d(require('./Readme'))
const resources = _d(require('./Resources'))
const scene = _d(require('./Scene'))
const stateful = _d(require('./Stateful'))
const stateless = _d(require('./Stateless'))
const story = _d(require('./Story'))
const view = _d(require('./View'))
const wrap = _d(require('./Wrap'))
const api = _d(require('./api'))
const dir = _d(require('./dir'))
const errorPage = _d(require('./errorPage'))
const lib = _d(require('./lib'))
const mapping = _d(require('./mapping'))
const nginx = _d(require('./nginx'))
const pcssVars = _d(require('./pcssVars'))
const selfSigned = _d(require('./selfSigned'))
const templates = _d(require('./templates'))
const test = _d(require('./test'))
const toc = _d(require('./toc'))
const vhost = _d(require('./vhost'))

exports.Ctrl = ctrl
exports.Dialogs = dialogs
exports.Hook = hook
exports.License = license
exports.Readme = readme
exports.Resources = resources
exports.Scene = scene
exports.Stateful = stateful
exports.Stateless = stateless
exports.Story = story
exports.View = view
exports.Wrap = wrap
exports.api = api
exports.dir = dir
exports.errorPage = errorPage
exports.lib = lib
exports.mapping = mapping
exports.nginx = nginx
exports.pcssVars = pcssVars
exports.selfSigned = selfSigned
exports.templates = templates
exports.test = test
exports.toc = toc
exports.vhost = vhost

