// Code generated by coz. DO NOT EDIT.
/**
 * Templates for the-projects
 * @module the-templates
 */
'use strict'

import Ctrl from './Ctrl'
import Hook from './Hook'
import Resources from './Resources'
import Scene from './Scene'
import Stateful from './Stateful'
import Stateless from './Stateless'
import View from './View'
import Wrap from './Wrap'
import api from './api'
import dir from './dir'
import errorPage from './errorPage'
import lib from './lib'
import mapping from './mapping'
import nginx from './nginx'
import pcssVars from './pcssVars'
import readme from './readme'
import selfSigned from './selfSigned'
import templates from './templates'
import test from './test'
import toc from './toc'
import vhost from './vhost'

export {
  Ctrl,
  Hook,
  Resources,
  Scene,
  Stateful,
  Stateless,
  View,
  Wrap,
  api,
  dir,
  errorPage,
  lib,
  mapping,
  nginx,
  pcssVars,
  readme,
  selfSigned,
  templates,
  test,
  toc,
  vhost,
}

