// Code generated by coz. DO NOT EDIT.
/**
 * Templates for the-projects
 * @module the-templates
 */
'use strict'

const _d = (m) => (m && 'default' in m) ? m.default : m

const Ctrl_ = require('./Ctrl')
const Dialogs_ = require('./Dialogs')
const Hook_ = require('./Hook')
const License_ = require('./License')
const Readme_ = require('./Readme')
const Resources_ = require('./Resources')
const Scene_ = require('./Scene')
const Stateful_ = require('./Stateful')
const Stateless_ = require('./Stateless')
const Story_ = require('./Story')
const View_ = require('./View')
const Wrap_ = require('./Wrap')
const api_ = require('./api')
const dir_ = require('./dir')
const errorPage_ = require('./errorPage')
const lib_ = require('./lib')
const mapping_ = require('./mapping')
const nginx_ = require('./nginx')
const pcssVars_ = require('./pcssVars')
const selfSigned_ = require('./selfSigned')
const templates_ = require('./templates')
const test_ = require('./test')
const toc_ = require('./toc')
const vhost_ = require('./vhost')


exports.Ctrl = _d(Ctrl_)
exports.Dialogs = _d(Dialogs_)
exports.Hook = _d(Hook_)
exports.License = _d(License_)
exports.Readme = _d(Readme_)
exports.Resources = _d(Resources_)
exports.Scene = _d(Scene_)
exports.Stateful = _d(Stateful_)
exports.Stateless = _d(Stateless_)
exports.Story = _d(Story_)
exports.View = _d(View_)
exports.Wrap = _d(Wrap_)
exports.api = _d(api_)
exports.dir = _d(dir_)
exports.errorPage = _d(errorPage_)
exports.lib = _d(lib_)
exports.mapping = _d(mapping_)
exports.nginx = _d(nginx_)
exports.pcssVars = _d(pcssVars_)
exports.selfSigned = _d(selfSigned_)
exports.templates = _d(templates_)
exports.test = _d(test_)
exports.toc = _d(toc_)
exports.vhost = _d(vhost_)
