// Code generated by coz. DO NOT EDIT.
/**
 * Templates for the-projects
 * @module the-templates
 */
'use strict'

const _interopRequireDefault = (obj) => obj && obj.__esModule ? obj : {default: obj}
const _d = (m) => _interopRequireDefault(m).default

const ctrl_ = _d(require('./Ctrl'))
const dialogs_ = _d(require('./Dialogs'))
const hook_ = _d(require('./Hook'))
const license_ = _d(require('./License'))
const readme_ = _d(require('./Readme'))
const resources_ = _d(require('./Resources'))
const scene_ = _d(require('./Scene'))
const stateful_ = _d(require('./Stateful'))
const stateless_ = _d(require('./Stateless'))
const story_ = _d(require('./Story'))
const view_ = _d(require('./View'))
const wrap_ = _d(require('./Wrap'))
const api_ = _d(require('./api'))
const dir_ = _d(require('./dir'))
const errorPage_ = _d(require('./errorPage'))
const lib_ = _d(require('./lib'))
const mapping_ = _d(require('./mapping'))
const nginx_ = _d(require('./nginx'))
const pcssVars_ = _d(require('./pcssVars'))
const selfSigned_ = _d(require('./selfSigned'))
const templates_ = _d(require('./templates'))
const test_ = _d(require('./test'))
const toc_ = _d(require('./toc'))
const vhost_ = _d(require('./vhost'))

exports.Ctrl = ctrl_
exports.Dialogs = dialogs_
exports.Hook = hook_
exports.License = license_
exports.Readme = readme_
exports.Resources = resources_
exports.Scene = scene_
exports.Stateful = stateful_
exports.Stateless = stateless_
exports.Story = story_
exports.View = view_
exports.Wrap = wrap_
exports.api = api_
exports.dir = dir_
exports.errorPage = errorPage_
exports.lib = lib_
exports.mapping = mapping_
exports.nginx = nginx_
exports.pcssVars = pcssVars_
exports.selfSigned = selfSigned_
exports.templates = templates_
exports.test = test_
exports.toc = toc_
exports.vhost = vhost_

