// Code generated by coz. DO NOT EDIT.
/**
 * Templates for the-projects
 * @module the-templates
 */
'use strict'

import Ctrl from './Ctrl'
import Dialogs from './Dialogs'
import Hook from './Hook'
import Readme from './Readme'
import Resources from './Resources'
import Scene from './Scene'
import Stateful from './Stateful'
import Stateless from './Stateless'
import Story from './Story'
import View from './View'
import Wrap from './Wrap'
import api from './api'
import dir from './dir'
import errorPage from './errorPage'
import lib from './lib'
import mapping from './mapping'
import nginx from './nginx'
import pcssVars from './pcssVars'
import selfSigned from './selfSigned'
import templates from './templates'
import test from './test'
import toc from './toc'
import vhost from './vhost'

export {
  Ctrl,
  Dialogs,
  Hook,
  Readme,
  Resources,
  Scene,
  Stateful,
  Stateless,
  Story,
  View,
  Wrap,
  api,
  dir,
  errorPage,
  lib,
  mapping,
  nginx,
  pcssVars,
  selfSigned,
  templates,
  test,
  toc,
  vhost,
}

